server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.114.129
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  jwt:
    pubKeyPath: E:/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN